[environments.supabase]
url = "jdbc:postgresql://[2406:da12:b78:de0d:bb7e:f8ef:6cc1:f90b]:5432/postgres?ssl=true&sslmode=require"
user = "postgres"
password = "${env.DB_PASSWORD}"
schemas = ["public"]

[flyway]
environment = "supabase"
locations = ["filesystem:sql/migrations"]
baselineVersion = "1"
baselineDescription = "create_initial_tables"
cleanDisabled = true
